"""Keyword-routed templated code generator.

Picks one of a small set of Flutter app archetypes based on the idea text
and fills in placeholders. Always available; needs no external services.
"""

from __future__ import annotations

import re

from ..models import GeneratedFile, IdeaSpec, ProjectFiles
from .base import CodeGenerator

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _slug(text: str, fallback: str = "app") -> str:
    s = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return s or fallback


def _title_from_idea(idea: str, app_name: str | None) -> str:
    if app_name:
        return app_name
    # First sentence, capped to ~40 chars.
    head = re.split(r"[.!?\n]", idea, maxsplit=1)[0].strip()
    return head[:40] or "My App"


def _color(hex_or_none: str | None) -> str:
    """Return a Dart `Color(0xFFRRGGBB)` literal."""
    h = (hex_or_none or "#1976D2").lstrip("#")
    return f"Color(0xFF{h.upper()})"


# ---------------------------------------------------------------------------
# Archetype router
# ---------------------------------------------------------------------------

_ARCHETYPE_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("translator", re.compile(r"\btransla(te|tor)\b|siswati|zulu|swahili|english", re.I)),
    ("notes", re.compile(r"\bnotes?\b|todo|task|reminder|journal", re.I)),
    ("calculator", re.compile(r"\bcalc(ulator)?\b|arithmetic|math", re.I)),
    ("flashlight", re.compile(r"\bflash[- ]?light\b|torch", re.I)),
]


def _route(idea: str) -> str:
    for name, pat in _ARCHETYPE_PATTERNS:
        if pat.search(idea):
            return name
    return "default"


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


class TemplatedGenerator(CodeGenerator):
    name = "templated"

    def generate(self, spec: IdeaSpec) -> ProjectFiles:
        archetype = _route(spec.idea)
        title = _title_from_idea(spec.idea, spec.app_name)
        package = _slug(title, fallback="my_app")
        color = _color(spec.primary_color)

        files: list[GeneratedFile] = []

        # Common project files
        files.append(GeneratedFile(path="pubspec.yaml", content=_pubspec(package)))
        files.append(GeneratedFile(path=".gitignore", content=_FLUTTER_GITIGNORE))
        files.append(
            GeneratedFile(
                path="README.md",
                content=_readme(title, archetype, spec.idea),
            )
        )
        files.append(
            GeneratedFile(
                path="analysis_options.yaml",
                content=_ANALYSIS_OPTIONS,
            )
        )

        # Archetype-specific lib/main.dart
        if archetype == "translator":
            main = _MAIN_TRANSLATOR
        elif archetype == "notes":
            main = _MAIN_NOTES
        elif archetype == "calculator":
            main = _MAIN_CALCULATOR
        elif archetype == "flashlight":
            main = _MAIN_FLASHLIGHT
        else:
            main = _MAIN_DEFAULT

        main = main.replace("__APP_TITLE__", title).replace("__PRIMARY_COLOR__", color)
        files.append(GeneratedFile(path="lib/main.dart", content=main))

        return ProjectFiles(archetype=archetype, files=files)


# ---------------------------------------------------------------------------
# Static templates
# ---------------------------------------------------------------------------


def _pubspec(package: str) -> str:
    return f"""name: {package}
description: Generated by Auto AI App Builder.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
"""


def _readme(title: str, archetype: str, idea: str) -> str:
    return f"""# {title}

Generated by **Auto AI App Builder** from the idea:

> {idea}

Archetype: `{archetype}`.

## Build

```bash
flutter pub get
flutter build apk --release
```
"""


_FLUTTER_GITIGNORE = """.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.packages
.pub-cache/
.pub/
build/
*.iml
local.properties
"""

_ANALYSIS_OPTIONS = """include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
"""


# ---- main.dart variants ---------------------------------------------------

_MAIN_DEFAULT = """import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '__APP_TITLE__',
      theme: ThemeData(colorSchemeSeed: const __PRIMARY_COLOR__, useMaterial3: true),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('__APP_TITLE__')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('You have pushed the button this many times:'),
            Text('$_count', style: Theme.of(context).textTheme.headlineMedium),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() => _count++),
        child: const Icon(Icons.add),
      ),
    );
  }
}
"""

_MAIN_NOTES = """import 'package:flutter/material.dart';

void main() => runApp(const NotesApp());

class NotesApp extends StatelessWidget {
  const NotesApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '__APP_TITLE__',
      theme: ThemeData(colorSchemeSeed: const __PRIMARY_COLOR__, useMaterial3: true),
      home: const NotesHome(),
    );
  }
}

class NotesHome extends StatefulWidget {
  const NotesHome({super.key});
  @override
  State<NotesHome> createState() => _NotesHomeState();
}

class _NotesHomeState extends State<NotesHome> {
  final _controller = TextEditingController();
  final List<String> _notes = [];

  void _add() {
    final text = _controller.text.trim();
    if (text.isEmpty) return;
    setState(() {
      _notes.insert(0, text);
      _controller.clear();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('__APP_TITLE__')),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(12),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _controller,
                    decoration: const InputDecoration(
                      hintText: 'Write a note…',
                      border: OutlineInputBorder(),
                    ),
                    onSubmitted: (_) => _add(),
                  ),
                ),
                const SizedBox(width: 8),
                FilledButton(onPressed: _add, child: const Text('Add')),
              ],
            ),
          ),
          Expanded(
            child: ListView.separated(
              itemCount: _notes.length,
              separatorBuilder: (_, __) => const Divider(height: 1),
              itemBuilder: (_, i) => ListTile(
                title: Text(_notes[i]),
                trailing: IconButton(
                  icon: const Icon(Icons.delete_outline),
                  onPressed: () => setState(() => _notes.removeAt(i)),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
"""

_MAIN_CALCULATOR = """import 'package:flutter/material.dart';

void main() => runApp(const CalcApp());

class CalcApp extends StatelessWidget {
  const CalcApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '__APP_TITLE__',
      theme: ThemeData(colorSchemeSeed: const __PRIMARY_COLOR__, useMaterial3: true),
      home: const CalcHome(),
    );
  }
}

class CalcHome extends StatefulWidget {
  const CalcHome({super.key});
  @override
  State<CalcHome> createState() => _CalcHomeState();
}

class _CalcHomeState extends State<CalcHome> {
  String _expr = '';
  String _result = '0';

  static const _keys = [
    ['7', '8', '9', '/'],
    ['4', '5', '6', '*'],
    ['1', '2', '3', '-'],
    ['0', '.', '=', '+'],
  ];

  void _onKey(String k) {
    setState(() {
      if (k == '=') {
        _result = _evaluate(_expr);
      } else {
        _expr += k;
      }
    });
  }

  String _evaluate(String e) {
    // Tiny shunting-yard for + - * /
    final tokens = RegExp(r'(\\d+\\.?\\d*|[+\\-*/])').allMatches(e).map((m) => m.group(0)!).toList();
    final ops = <String>[];
    final out = <String>[];
    int prec(String op) => (op == '*' || op == '/') ? 2 : 1;
    for (final t in tokens) {
      if (RegExp(r'^\\d').hasMatch(t)) {
        out.add(t);
      } else {
        while (ops.isNotEmpty && prec(ops.last) >= prec(t)) {
          out.add(ops.removeLast());
        }
        ops.add(t);
      }
    }
    while (ops.isNotEmpty) {
      out.add(ops.removeLast());
    }
    final stack = <double>[];
    for (final t in out) {
      if (RegExp(r'^\\d').hasMatch(t)) {
        stack.add(double.parse(t));
      } else if (stack.length >= 2) {
        final b = stack.removeLast();
        final a = stack.removeLast();
        switch (t) {
          case '+': stack.add(a + b); break;
          case '-': stack.add(a - b); break;
          case '*': stack.add(a * b); break;
          case '/': stack.add(b == 0 ? double.nan : a / b); break;
        }
      }
    }
    if (stack.isEmpty) return '0';
    final v = stack.last;
    return v == v.roundToDouble() ? v.toInt().toString() : v.toString();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('__APP_TITLE__')),
      body: Column(
        children: [
          Container(
            alignment: Alignment.centerRight,
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Text(_expr, style: const TextStyle(fontSize: 24, color: Colors.grey)),
                Text(_result, style: const TextStyle(fontSize: 48)),
              ],
            ),
          ),
          Expanded(
            child: Column(
              children: _keys
                  .map(
                    (row) => Expanded(
                      child: Row(
                        children: row
                            .map((k) => Expanded(
                                  child: Padding(
                                    padding: const EdgeInsets.all(6),
                                    child: FilledButton(
                                      onPressed: () => _onKey(k),
                                      child: Text(k, style: const TextStyle(fontSize: 24)),
                                    ),
                                  ),
                                ))
                            .toList(),
                      ),
                    ),
                  )
                  .toList(),
            ),
          ),
        ],
      ),
    );
  }
}
"""

_MAIN_FLASHLIGHT = """import 'package:flutter/material.dart';

void main() => runApp(const FlashlightApp());

class FlashlightApp extends StatelessWidget {
  const FlashlightApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '__APP_TITLE__',
      theme: ThemeData(colorSchemeSeed: const __PRIMARY_COLOR__, useMaterial3: true),
      home: const FlashlightHome(),
    );
  }
}

class FlashlightHome extends StatefulWidget {
  const FlashlightHome({super.key});
  @override
  State<FlashlightHome> createState() => _FlashlightHomeState();
}

class _FlashlightHomeState extends State<FlashlightHome> {
  bool _on = false;

  @override
  Widget build(BuildContext context) {
    final bg = _on ? Colors.white : Colors.black;
    final fg = _on ? Colors.black : Colors.white;
    return Scaffold(
      backgroundColor: bg,
      body: SafeArea(
        child: GestureDetector(
          onTap: () => setState(() => _on = !_on),
          child: Container(
            color: bg,
            alignment: Alignment.center,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.flashlight_on, size: 96, color: fg),
                const SizedBox(height: 24),
                Text('Tap anywhere to toggle',
                    style: TextStyle(color: fg, fontSize: 18)),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
"""

_MAIN_TRANSLATOR = """import 'package:flutter/material.dart';

void main() => runApp(const TranslatorApp());

class TranslatorApp extends StatelessWidget {
  const TranslatorApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '__APP_TITLE__',
      theme: ThemeData(colorSchemeSeed: const __PRIMARY_COLOR__, useMaterial3: true),
      home: const TranslatorHome(),
    );
  }
}

// Tiny offline phrase dictionary so the app does something useful with no
// network. Production builds would swap this for a real translation API.
const Map<String, String> _enToSiswati = {
  'hello': 'sawubona',
  'thank you': 'ngiyabonga',
  'good morning': 'sawubona ekuseni',
  'how are you': 'unjani',
  'i am fine': 'ngikhona',
  'goodbye': 'sala kahle',
};

class TranslatorHome extends StatefulWidget {
  const TranslatorHome({super.key});
  @override
  State<TranslatorHome> createState() => _TranslatorHomeState();
}

class _TranslatorHomeState extends State<TranslatorHome> {
  final _controller = TextEditingController();
  String _out = '';
  bool _enToSwati = true;

  void _translate() {
    final input = _controller.text.trim().toLowerCase();
    if (input.isEmpty) {
      setState(() => _out = '');
      return;
    }
    final dict = _enToSwati
        ? _enToSiswati
        : {for (final e in _enToSiswati.entries) e.value: e.key};
    setState(() {
      _out = dict[input] ?? '— no offline match —';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('__APP_TITLE__'),
        actions: [
          Row(
            children: [
              Text(_enToSwati ? 'EN → SS' : 'SS → EN'),
              Switch(
                value: _enToSwati,
                onChanged: (v) => setState(() {
                  _enToSwati = v;
                  _translate();
                }),
              ),
            ],
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            TextField(
              controller: _controller,
              maxLines: 3,
              decoration: const InputDecoration(
                hintText: 'Type a phrase…',
                border: OutlineInputBorder(),
              ),
              onChanged: (_) => _translate(),
            ),
            const SizedBox(height: 16),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                border: Border.all(color: Colors.grey),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Text(
                _out.isEmpty ? '…' : _out,
                style: const TextStyle(fontSize: 22),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
"""
